export const LEAGUES = [
  {
    id: 'premier-league',
    name: 'Premier League',
    country: 'Inglaterra',
    logo: '/logos/campeonatos/premier-league.png',
    teams: [
      { id: 'arsenal', name: 'Arsenal', logo: '/logos/premierleague/Arsenal_FC.svg.png' },
      { id: 'aston-villa', name: 'Aston Villa', logo: '/logos/premierleague/Aston_Villa.svg.png' },
      { id: 'brighton', name: 'Brighton', logo: '/logos/premierleague/Brighton_&_Hove_Albion.png' },
      { id: 'chelsea', name: 'Chelsea', logo: '/logos/premierleague/Chelsea_FC.svg.png' },
      { id: 'crystal-palace', name: 'Crystal Palace', logo: '/logos/premierleague/Crystal_Palace_FC_logo.png' },
      { id: 'everton', name: 'Everton', logo: '/logos/premierleague/Everton_FC_logo_2014.png' },
      { id: 'fulham', name: 'Fulham', logo: '/logos/premierleague/Fulham_FC.svg.png' },
      { id: 'leeds-united', name: 'Leeds United', logo: '/logos/premierleague/Leeds_United_Logo.png' },
      { id: 'leicester-city', name: 'Leicester City', logo: '/logos/premierleague/LeicesterCity_logo2014.png' },
      { id: 'liverpool', name: 'Liverpool', logo: '/logos/premierleague/Liverpool_FC.svg.png' },
      { id: 'manchester-city', name: 'Manchester City', logo: '/logos/premierleague/Manchester_City_Football_Club.png' },
      { id: 'manchester-united', name: 'Manchester United', logo: '/logos/premierleague/Manchester_United_FC_logo.png' },
      { id: 'newcastle', name: 'Newcastle', logo: '/logos/premierleague/Newcastle_United_Logo.png' },
      { id: 'nottingham-forest', name: 'Nottingham Forest', logo: '/logos/premierleague/Nottingham_Forest.png' },
      { id: 'sheffield-united', name: 'Sheffield United', logo: '/logos/premierleague/Sheffield_United_FC.png' },
      { id: 'tottenham', name: 'Tottenham', logo: '/logos/premierleague/Tottenham_Hotspur.png' },
      { id: 'west-ham', name: 'West Ham', logo: '/logos/premierleague/West_Ham_United_FC_logo.png' },
      { id: 'wolverhampton', name: 'Wolverhampton', logo: '/logos/premierleague/Wolverhampton_Wanderers.png' },
    ],
  },
  {
    id: 'laliga',
    name: 'La Liga',
    country: 'Espanha',
    logo: '/logos/campeonatos/laliga.png',
    teams: [
      {
        id: 'real-madrid',
        name: 'Real Madrid',
        logo: '/logos/laliga/Real_Madrid.png',
      },
      {
        id: 'barcelona',
        name: 'Barcelona',
        logo: '/logos/laliga/FCBarcelona.svg.png',
      },
      {
        id: 'atletico-madrid',
        name: 'Atlético de Madrid',
        logo: '/logos/laliga/Atletico_Madrid_logo.svg.png',
      },
      {
        id: 'athletic-bilbao',
        name: 'Athletic Bilbao',
        logo: '/logos/laliga/Athletic_Club_de_Bilbao.png',
      },
      {
        id: 'celta-de-vigo',
        name: 'Celta de Vigo',
        logo: '/logos/laliga/Celta_de_Vigo.png',
      },
      {
        id: 'espanyol',
        name: 'Espanyol',
        logo: '/logos/laliga/Rcd_espanyol_logo.png',
      },
      {
        id: 'rayo-vallecano',
        name: 'Rayo Vallecano',
        logo: '/logos/laliga/Rayo_Vallecano_de_Madrid.png',
      },
      {
        id: 'real-betis',
        name: 'Real Betis',
        logo: '/logos/laliga/Real_Betis_Balompié.png',
      },
      {
        id: 'real-valladolid',
        name: 'Real Valladolid',
        logo: '/logos/laliga/Real_Valladolid_CF.png',
      },
      {
        id: 'sevilla',
        name: 'Sevilla',
        logo: '/logos/laliga/Sevilla_cf.png',
      },
      {
        id: 'villarreal',
        name: 'Villarreal',
        logo: '/logos/laliga/Villarreal_CF_logo.svg.png',
      },
    ],
  },
  {
    id: 'brasileirao',
    name: 'Brasileirao',
    country: 'Brasil',
    logo: '/logos/campeonatos/Campeonato_Brasileiro_de_Futebol.png',
    teams: [
      { id: 'america-mg', name: 'America Mineiro', logo: '/logos/brasileirao/Escudo_do_America_Futebol_Clube.svg.png' },
      { id: 'athletico-pr', name: 'Athletico PR', logo: '/logos/brasileirao/Athletico_Paranaense_(Logo_2019).svg.png' },
      { id: 'bahia', name: 'Bahia', logo: '/logos/brasileirao/ECBahia.png' },
      { id: 'botafogo', name: 'Botafogo', logo: '/logos/brasileirao/Botafogo_de_Futebol_e_Regatas_logo.svg.png' },
      { id: 'ceara', name: 'Ceara', logo: '/logos/brasileirao/images.png' },
      { id: 'corinthians', name: 'Corinthians', logo: '/logos/brasileirao/Corinthians_simbolo.png' },
      { id: 'cruzeiro', name: 'Cruzeiro', logo: '/logos/brasileirao/Cruzeiro_Esporte_Clube_(logo).svg.png' },
      { id: 'flamengo', name: 'Flamengo', logo: '/logos/brasileirao/Flamengo-RJ_(BRA).png' },
      { id: 'fluminense', name: 'Fluminense', logo: '/logos/brasileirao/Fluminense_FC_escudo.png' },
      { id: 'fortaleza', name: 'Fortaleza', logo: '/logos/brasileirao/Fortaleza_Esporte_Clube_logo.png' },
      { id: 'gremio', name: 'Gremio', logo: '/logos/brasileirao/Gremio_logo.svg.png' },
      { id: 'internacional', name: 'Internacional', logo: '/logos/brasileirao/Escudo_do_Sport_Club_Internacional.svg.png' },
      { id: 'palmeiras', name: 'Palmeiras', logo: '/logos/brasileirao/Palmeiras_logo.svg.png' },
      { id: 'paysandu', name: 'Paysandu', logo: '/logos/brasileirao/PaysanduSC.png' },
      { id: 'bragantino', name: 'RB Bragantino', logo: '/logos/brasileirao/RedBullBragantino.png' },
      { id: 'remo', name: 'Remo', logo: '/logos/brasileirao/Clube_do_Remo.svg.png' },
      { id: 'santa-cruz', name: 'Santa Cruz', logo: '/logos/brasileirao/santa-cruz.png' },
      { id: 'santos', name: 'Santos', logo: '/logos/brasileirao/Santos_Logo.png' },
      { id: 'sport', name: 'Sport', logo: '/logos/brasileirao/Sport_Club_do_Recife.png' },
      { id: 'sao-paulo', name: 'Sao Paulo', logo: '/logos/brasileirao/Brasao_do_Sao_Paulo_Futebol_Clube.svg.png' },
      { id: 'vasco', name: 'Vasco', logo: '/logos/brasileirao/vasco-logo-1.png' },
      { id: 'vitoria', name: 'Vitoria', logo: '/logos/brasileirao/ec-vitoria-logo-1.png' },
    ],
  },
  {
    id: 'selecoes',
    name: 'Selecoes Mundiais',
    country: 'Mundo',
    logo: '/logos/campeonatos/logo-fifa.png',
    teams: [
      { id: 'alemanha', name: 'Alemanha', logo: `/logos/mundial/alemanha.png` },
      { id: 'argéria', name: 'Argéria', logo: `/logos/mundial/Algeria_National_Football_Team_logo.png` },
      { id: 'argentina', name: 'Argentina', logo: `/logos/mundial/230px-Afa_logo.svg.png` },
      { id: 'arabia-saudita', name: 'Arábia Saudita', logo: `/logos/mundial/Flag_of_Saudi_Arabia.png` },
      { id: 'belgica', name: 'Belgica', logo: `/logos/mundial/belgian-national-team-logo-2.png` },
      { id: 'brasil', name: 'Brasil', logo: `/logos/mundial/Brazilian_Football_Confederation_logo.svg` },
      { id: 'camaroes', name: 'Camarões', logo: `/logos/mundial/Cameroon_2010crest.png` },
      { id: 'canada', name: 'Canadá', logo: `/logos/mundial/Flag_of_Canada.png` },
      { id: 'chile', name: 'Chile', logo: `/logos/mundial/Flag_of_Chile.png` },
      { id: 'china', name: 'China', logo: `/logos/mundial/Flag_of_the_People's_Republic_of_China.svg.png` },
      { id: 'coreia-do-sul', name: 'Coreia do Sul', logo: `/logos/mundial/Flag_of_South_Korea.svg` },
      { id: 'costa-do-marfim', name: 'Costa Do Marfim', logo: `/logos/mundial/costa do marfim.png` },
      { id: 'costa-rica', name: 'Costa Rica', logo: `/logos/mundial/Costa_Rica_national_football_team_logo.svg.png` },
      { id: 'croacia', name: 'Croácia', logo: `/logos/mundial/Croatia_football_federation.png` },
      { id: 'dinamarca', name: 'Dinamarca', logo: `/logos/mundial/Dansk_boldspil_union_logo.svg.png` },
      { id: 'egito', name: 'Egito', logo: `/logos/mundial/Egyptian_Football_Association.png` },
      { id: 'equador', name: 'Equador', logo: `/logos/mundial/Logo_de_la_Federación_Ecuatoriana_de_Fútbol_(2).svg.png` },
      { id: 'escocia', name: 'Escócia', logo: `/logos/mundial/Seleção_Escocesa_logo.png` },
      { id: 'espanha', name: 'Espanha', logo: `/logos/mundial/Spain_National_Football_Team_badge.png` },
      { id: 'estados-unidos', name: 'Estados Unidos', logo: `/logos/mundial/United_States_Soccer_Federation_logo.svg.png` },
      { id: 'franca', name: 'França', logo: `/logos/mundial/Logo_Seleção_Francesa_2018.png` },
      { id: 'grecia', name: 'Grécia', logo: `/logos/mundial/Greece_National_Football_Team.svg.png` },
      { id: 'holanda', name: 'Holanda', logo: `/logos/mundial/Netherlands_national_football_team_logo_2017.png` },
      { id: 'inglaterra', name: 'Inglaterra', logo: `/logos/mundial/england-national-team-logo-0-2048x2048.png` },
      { id: 'irlanda', name: 'Irlanda', logo: `/logos/mundial/FAIreland.png` },
      { id: 'italia', name: 'Itália', logo: `/logos/mundial/Logo_Italy_National_Football_Team_-_2023.svg.png` },
      { id: 'jamaica', name: 'Jamaica', logo: `/logos/mundial/Jamaica_FA.svg.png` },
      { id: 'japao', name: 'Japão', logo: `/logos/mundial/JapanFA.png` },
      { id: 'marrocos', name: 'Marrocos', logo: `/logos/mundial/Fédération_Royale_Marocaine_de_Football.png` },
      { id: 'mexico', name: 'México', logo: `/logos/mundial/Mexico_national_football_team_crest_(2022).png` },
      { id: 'nigeria', name: 'Nigéria', logo: `/logos/mundial/NigeriaFA.png` },
      { id: 'noruega', name: 'Noruega', logo: `/logos/mundial/Seleção_Norueguesa_de_Futebol_Logo.png` },
      { id: 'pais-de-gales', name: 'País De Gales', logo: `/logos/mundial/FAWales.png` },
      { id: 'peru', name: 'Peru', logo: `/logos/mundial/selecao-peruana-de-futebol.png` },
      { id: 'polonia', name: 'Polônia', logo: `/logos/mundial/Polish_Football_Association_logo.svg.png` },
      { id: 'portugal', name: 'Portugal', logo: `/logos/mundial/Portugal_National_Team_logo.png` },
      { id: 'qatar', name: 'Qatar', logo: `/logos/mundial/Associação_do_Qatar_de_Futebol.png` },
      { id: 'romenia', name: 'Romênia', logo: `/logos/mundial/FRomânăF.png` },
      { id: 'senegal', name: 'Senegal', logo: `/logos/mundial/FSenegalaiseF.png` },
      { id: 'suica', name: 'Suiça', logo: `/logos/mundial/SFV_Logo.svg.png` },
      { id: 'turquia', name: 'Turquia', logo: `/logos/mundial/Roundel_flag_of_Turkey.svg` },
      { id: 'uruguai', name: 'Uruguai', logo: `/logos/mundial/AUF.png` },
    ],
  },
  {
    id: 'bundesliga',
    name: 'Bundesliga',
    country: 'Alemanha',
    logo: '/logos/campeonatos/Bundesliga_logo.png',
    teams: [
      { id: 'bayern-de-munique', name: 'Bayern de Munique', logo: `/logos/Bundesliga/Bayern-Munchen-munique-logo-escudo.png` },
      { id: 'borussia-dortmund', name: 'Borussia Dortmund', logo: `/logos/Bundesliga/bvb-borussia-dortmund-logo-1.png` },
      { id: 'borussia-m_gladbach', name: 'Borussia M_Gladbach', logo: `/logos/Bundesliga/Borussia_Mönchengladbach_logo.svg.png` },
      { id: 'eintracht-frankfurt', name: 'Eintracht Frankfurt', logo: `/logos/Bundesliga/eintracht-frankfurt-logo.png` },
      { id: 'hertha-berlin', name: 'Hertha Berlin', logo: `/logos/Bundesliga/Hertha_BSC_Logo.svg.png` },
      { id: 'hoffenheim', name: 'Hoffenheim', logo: `/logos/Bundesliga/Logo_TSG_Hoffenheim.svg.png` },
      { id: 'mainz-05', name: 'Mainz 05', logo: `/logos/Bundesliga/FSV_Mainz_05_Logo.png` },
      { id: 'rb-leipzig', name: 'RB Leipzig', logo: `/logos/Bundesliga/RB_Leipzig_2020_Logo.png` },
      { id: 'schalke-04', name: 'Schalke 04', logo: `/logos/Bundesliga/FC_Schalke_04_Logo.png` },
      { id: 'union-berlin', name: 'Union Berlin', logo: `/logos/Bundesliga/Escudo_Union_Berlin.png` },
      { id: 'wolfsburg', name: 'Wolfsburg', logo: `/logos/Bundesliga/Logo-VfL-Wolfsburg.svg.png` },
    ],
  },
  {
    id: 'ligue-1',
    name: 'Ligue 1',
    country: 'França',
    logo: '/logos/campeonatos/ligue-1-logo.png',
    teams: [
      { id: 'lens', name: 'Lens', logo: `/logos/Ligue 1/RC_Lens.png` },
      { id: 'lille', name: 'Lille', logo: `/logos/Ligue 1/lille-logo.png` },
      { id: 'lorient', name: 'Lorient', logo: `/logos/Ligue 1/FC_Lorient.png` },
      { id: 'lyon', name: 'Lyon', logo: `/logos/Ligue 1/Olympique_lyonnais.png` },
      { id: 'monaco', name: 'Monaco', logo: `/logos/Ligue 1/monaco-fc-logo-1.png` },
      { id: 'nantes', name: 'Nantes', logo: `/logos/Ligue 1/FC-Nantes-blason-rvb.png` },
      { id: 'olympique-de-marseille', name: 'Olympique de Marseille', logo: `/logos/Ligue 1/Olympique_Marseille_logo.svg.png` },
      { id: 'paris-saint-germain', name: 'Paris Saint Germain', logo: `/logos/Ligue 1/psg-logo-escudo-paris-saint-germain.png` },
      { id: 'rennes', name: 'Rennes', logo: `/logos/Ligue 1/Stade_Rennais_FC.png` },
      { id: 'stade-reims', name: 'Stade Reims', logo: `/logos/Ligue 1/Stade_de_Reims.png` },
      { id: 'strasbourg', name: 'Strasbourg', logo: `/logos/Ligue 1/Strasbourg-logo.png` },
    ],
  },
  {
    id: 'serie-a',
    name: 'Serie A',
    country: 'Itália',
    logo: '/logos/campeonatos/serie-a-logo-png.png',
    teams: [
      { id: 'atalanta', name: 'Atalanta', logo: `/logos/Serie A/atalanta-logo-1.png` },
      { id: 'empoli', name: 'Empoli', logo: `/logos/Serie A/Empoli_FC_logo.svg.png` },
      { id: 'fiorentina', name: 'Fiorentina', logo: `/logos/Serie A/ACF_Fiorentina.png` },
      { id: 'inter-de-milao', name: 'Inter de Milão', logo: `/logos/Serie A/inter-milan-logo.png` },
      { id: 'juventus', name: 'Juventus', logo: `/logos/Serie A/Juventus_FC_2017_logo.png` },
      { id: 'lazio', name: 'Lazio', logo: `/logos/Serie A/lazio-logo.png` },
      { id: 'milan', name: 'Milan', logo: `/logos/Serie A/ac-milan-logo.png` },
      { id: 'napoli', name: 'Napoli', logo: `/logos/Serie A/napoli-logo-escudo.png` },
      { id: 'roma', name: 'Roma', logo: `/logos/Serie A/as-roma-logo.png` },
      { id: 'sampdoria', name: 'Sampdoria', logo: `/logos/Serie A/UC_Sampdoria.png` },
    ],
  },
]
